#!/bin/bash

wall_path="/home/${USER}/wallpapers/"
random_wall() {
	arr=()
	while IFS='' read -r value; do
		arr+=("$value")
	done <<< $(find ${wall_path} -type f ! -regex '.*\.git.*')
	len=${#arr[@]}
	echo "$len" "wallpapers found!"
	var=$((${RANDOM}%${len}))
	ran_wall=${arr[$var]}
	echo "$ran_wall" "selected as wallpaper"
	if [[ "${XDG_CURRENT_DESKTOP}" =~ "GNOME" ]];
	then
		gsettings set org.gnome.desktop.background picture-uri "file://${ran_wall}"
		exit 0
	elif [ "$XDG_SESSION_TYPE" == "wayland" -a -f /bin/swaybg ]; then
		pid="`pidof swaybg`"
		if [ -n "${pid}" ]; then
			echo "swaybg is already running"
			kill "${pid}"
		fi
		swaybg -i "${ran_wall}" -m fill &
		exit 0
	elif [ -f /bin/feh ]; then
		feh --bg-fill "$ran_wall"
		exit 0
	fi
	echo "Couldn't change the wallpaper!"
}

random_wall
